server:
  port: 8040


eureka:
  client:
    service-url:
      defaultZone: http://uesr:password123@peer1:8761/eureka/,http://user:password123@peer2:8762/eureka/
    instance:
      prefer-ip-address: true
spring:
  application:
    name: microservice-getway-zuul