spring:
  application:
    name: microservice-discovery-eureka-ha

#使用Basic 安全校验
security:
  basic:
    enabled: true
  user:
    password: password123
    name: user

#开启自我保护模式
eureka:
  server:
    enable-self-preservation: true

---
spring:
  profiles: peer1
server:
  port: 8761

eureka:
  instance:
    hostname: peer1
  client:
    serviceUrl:
      defaultZone: http://peer2:8762/eureka/

---
spring:
  profiles: peer2
server:
  port: 8762
eureka:
  instance:
    hostname: peer2
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/


# 参考文档：http://projects.spring.io/spring-cloud/docs/1.0.3/spring-cloud.html#_standalone_mode
# 参考文档：http://my.oschina.net/buwei/blog/618756