server:
  port: 8010

user:
  userServiceUrl: http://localhost:8000/

spring:
  application:
    name: microservice-consumer-movie
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

eureka:
  client:
    service-url:
      defaultZone: http://uesr:password123@peer1:8761/eureka/,http://user:password123@peer2:8762/eureka/
    instance:
      prefer-ip-address: true
  instance:
    healthcheck:
      enabled: true

#开启断路监控
feign:
  hystrix:
    enabled: true


