server:
  port: 8031
spring:
  application:
    name: microservice-hystrix-turbine
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

eureka:
  client:
    service-url:
      defaultZone: http://peer1:8761/eureka/,http://peer2:8762/eureka/
  instance:
    prefer-ip-address: true

#turbine:
#  app-config: microservice-consumer-movie
#  cluster-name-expression: "'default'"

